# Avalon configurations

irc:
    nick: 'GoBzzzt'
    user: 'bzzzt'
    server: 'irc.freenode.net:8000'    
    channels:
        - '#linuxba'
        - '#bzzzt'
    ping: 30     # every n seconds send PING to irc server

mongo:
    server: 'avalon-mongo:27017'    
    user: 'logbot'    
    password: 'J1a4D0n,M1m@'
    auth_db: 'user'
    irc_db: 'irc_logs'
    time_zone: 'Asia/Shanghai'

server:
    channels:
        - '#linuxba'
        - '#bzzzt'
    port: 5556
    public: 'public'
    dist: 'public/dist'
